// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

using WebDriverManager;
using WebDriverManager.DriverConfigs.Impl;

[TestFixture]
public class SauTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    new DriverManager().SetUpDriver(new ChromeConfig());
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void TesteSauceDemo() {
    driver.Navigate().GoToUrl("https://www.saucedemo.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(988, 1040);
    driver.FindElement(By.CssSelector(".login_credentials_wrap-inner")).Click();
    driver.FindElement(By.CssSelector("*[data-test=\"username\"]")).Click();
    driver.FindElement(By.CssSelector("*[data-test=\"username\"]")).SendKeys("standard_user");
    driver.FindElement(By.CssSelector("*[data-test=\"password\"]")).Click();
    driver.FindElement(By.CssSelector("*[data-test=\"password\"]")).SendKeys("secret_sauce");
    driver.FindElement(By.CssSelector("*[data-test=\"login-button\"]")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".title")).Text, Is.EqualTo("Products"));
    driver.FindElement(By.CssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).Click();
    driver.FindElement(By.CssSelector("#item_4_title_link > .inventory_item_name")).Click();
    Assert.That(driver.FindElement(By.CssSelector("*[data-test=\"remove-sauce-labs-backpack\"]")).Text, Is.EqualTo("Remove"));
    /* var elements = driver.FindElements(By.CssSelector(".inventory_details_img"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.LinkText("1")).Click();
    Assert.That(driver.FindElement(By.CssSelector("*[data-test=\"remove-sauce-labs-backpack\"]")).Text, Is.EqualTo("Remove")); */
    var elements = driver.FindElements(By.CssSelector(".shopping_cart_badge"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector("*[data-test=\"remove-sauce-labs-backpack\"]")).Click();
    driver.Close();
  }
}
